language: java
jdk:
  -openjdk11

  before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "o-oualid"
  - git config --local user.email "qwertyoualid@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true